### ISSUE TITLE
issue : 계좌번호

### ISSUE THREAD

**Issue by LJH098** [Step3-kakao-tech-campus/Team12_BE#11]
## Description
지금 유저가 계좌번호를 여러개 받을 수 있는데 이렇게 되면 유저에서 계좌번호를 가져오기 위해 
@OneToMany(mappedby="user") private List<Account>accounts = new ArrayList<>를 해줘야해서 양방향 관계가 생기고
여러개의 계좌번호 중 선택한 어느 1개의 계좌번호를 보여줘야하는데 어짜피 그거는 유저 테이블에 계좌번호 필드를 추가해야 할 것 같다.
유저당 계좌번호를 1개만 받게 하면 해결될 것 같은데 어떻게 해야할까?

## 선택
- [ ] 기존대로 간다.
- [x] 유저당 계좌번호를 1개만 받을 수 있게한다.

## ETC
기타사항

![image](https://github.com/Step3-kakao-tech-campus/Team12_BE/assets/125119237/6cf2479f-b1ac-40ec-8f94-aa971fab8c9f)

**Comment by juuhyeon** [comment]
유저마다 계좌 하나만 받아도 괜찮을 거 같아요!
